### ISSUE TITLE
gentoo growpart-initramfs: does not bring up logical volumes in active state

### ISSUE THREAD

**Issue by blueness** [rackerlabs/base-image-blueprints#4]
I'm currently running a slice and I'm using growpart-initramfs.  My fstab has the following entries:

<pre>
/dev/xvda1      /           ext4    errors=remount-ro,noatime,barrier=0 0 1
/dev/xvdb1      none            swap    sw                  0 0
/dev/lvm/grs        /var/tmp/grs/       ext4    errors=remount-ro,noatime,barrier=0 0 1
/dev/lvm/catalyst   /var/tmp/catalyst/  ext4    errors=remount-ro,noatime,barrier=0     0 1
</pre>

Upon system reboot, the logical volumes grs and catalyst are there when the system comes back up, but they are not active.  If you manually set them active you can then mount.

<pre>
lvchange -a y /dev/lvm/grs
lvchange -a y /dev/lvm/catalyst
mount -a
</pre>

The init script in the initrd should bring them up active so they'll automount.

**Comment by prometheanfire** [comment]
could be done by checking if the binary exists.

    which lvchange
    if [[ $? == 0 ]]; then
        lvchange -a y
    fi

**Comment by prometheanfire** [comment]
probably not exactly that, but you get it I hope :D

also, just realized you don't need to check for the binary since you control the initram.

**Comment by oldarmyc** [comment]
Gentoo image has been retired and will not be updated. Closing issue
